/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoungHeartsRouteImport } from './routes/young-hearts'
import { Route as TazkiyahToolkitRouteImport } from './routes/tazkiyah-toolkit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuranicReflectionsRouteImport } from './routes/quranic-reflections'
import { Route as LifeArchitectureRouteImport } from './routes/life-architecture'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PageSlugRouteImport } from './routes/$pageSlug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadSlugRouteImport } from './routes/read.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReflectionsRouteImport } from './routes/_authenticated/admin/reflections'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminFormatsRouteImport } from './routes/_authenticated/admin/formats'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin/faqs'
import { Route as AuthenticatedAdminArchiveRouteImport } from './routes/_authenticated/admin/archive'
import { Route as AuthenticatedAdminPillarsIndexRouteImport } from './routes/_authenticated/admin/pillars.index'
import { Route as AuthenticatedAdminPagesIndexRouteImport } from './routes/_authenticated/admin/pages.index'
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from './routes/_authenticated/admin/articles/index'
import { Route as AuthenticatedAdminArticlesIdRouteImport } from './routes/_authenticated/admin/articles/$id'
import { Route as AuthenticatedAdminPillarsSlugEditRouteImport } from './routes/_authenticated/admin/pillars.$slug.edit'
import { Route as AuthenticatedAdminPagesKeyBuilderRouteImport } from './routes/_authenticated/admin/pages.$key.builder'

const YoungHeartsRoute = YoungHeartsRouteImport.update({
  id: '/young-hearts',
  path: '/young-hearts',
  getParentRoute: () => rootRouteImport,
} as any)
const TazkiyahToolkitRoute = TazkiyahToolkitRouteImport.update({
  id: '/tazkiyah-toolkit',
  path: '/tazkiyah-toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranicReflectionsRoute = QuranicReflectionsRouteImport.update({
  id: '/quranic-reflections',
  path: '/quranic-reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeArchitectureRoute = LifeArchitectureRouteImport.update({
  id: '/life-architecture',
  path: '/life-architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/$pageSlug',
  path: '/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/read/$slug',
  path: '/read/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReflectionsRoute =
  AuthenticatedAdminReflectionsRouteImport.update({
    id: '/reflections',
    path: '/reflections',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFormatsRoute =
  AuthenticatedAdminFormatsRouteImport.update({
    id: '/formats',
    path: '/formats',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminArchiveRoute =
  AuthenticatedAdminArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPillarsIndexRoute =
  AuthenticatedAdminPillarsIndexRouteImport.update({
    id: '/pillars/',
    path: '/pillars/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesIndexRoute =
  AuthenticatedAdminPagesIndexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminArticlesIdRoute =
  AuthenticatedAdminArticlesIdRouteImport.update({
    id: '/articles/$id',
    path: '/articles/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPillarsSlugEditRoute =
  AuthenticatedAdminPillarsSlugEditRouteImport.update({
    id: '/pillars/$slug/edit',
    path: '/pillars/$slug/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesKeyBuilderRoute =
  AuthenticatedAdminPagesKeyBuilderRouteImport.update({
    id: '/pages/$key/builder',
    path: '/pages/$key/builder',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/life-architecture': typeof LifeArchitectureRoute
  '/quranic-reflections': typeof QuranicReflectionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tazkiyah-toolkit': typeof TazkiyahToolkitRoute
  '/young-hearts': typeof YoungHeartsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/read/$slug': typeof ReadSlugRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/formats': typeof AuthenticatedAdminFormatsRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/reflections': typeof AuthenticatedAdminReflectionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/pillars/': typeof AuthenticatedAdminPillarsIndexRoute
  '/admin/pages/$key/builder': typeof AuthenticatedAdminPagesKeyBuilderRoute
  '/admin/pillars/$slug/edit': typeof AuthenticatedAdminPillarsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/life-architecture': typeof LifeArchitectureRoute
  '/quranic-reflections': typeof QuranicReflectionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tazkiyah-toolkit': typeof TazkiyahToolkitRoute
  '/young-hearts': typeof YoungHeartsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/read/$slug': typeof ReadSlugRoute
  '/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/formats': typeof AuthenticatedAdminFormatsRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/reflections': typeof AuthenticatedAdminReflectionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesIndexRoute
  '/admin/pages': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/pillars': typeof AuthenticatedAdminPillarsIndexRoute
  '/admin/pages/$key/builder': typeof AuthenticatedAdminPagesKeyBuilderRoute
  '/admin/pillars/$slug/edit': typeof AuthenticatedAdminPillarsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$pageSlug': typeof PageSlugRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/life-architecture': typeof LifeArchitectureRoute
  '/quranic-reflections': typeof QuranicReflectionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tazkiyah-toolkit': typeof TazkiyahToolkitRoute
  '/young-hearts': typeof YoungHeartsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/read/$slug': typeof ReadSlugRoute
  '/_authenticated/admin/archive': typeof AuthenticatedAdminArchiveRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/formats': typeof AuthenticatedAdminFormatsRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/reflections': typeof AuthenticatedAdminReflectionsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/articles/$id': typeof AuthenticatedAdminArticlesIdRoute
  '/_authenticated/admin/articles/': typeof AuthenticatedAdminArticlesIndexRoute
  '/_authenticated/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/_authenticated/admin/pillars/': typeof AuthenticatedAdminPillarsIndexRoute
  '/_authenticated/admin/pages/$key/builder': typeof AuthenticatedAdminPagesKeyBuilderRoute
  '/_authenticated/admin/pillars/$slug/edit': typeof AuthenticatedAdminPillarsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$pageSlug'
    | '/about'
    | '/auth'
    | '/contact'
    | '/join'
    | '/life-architecture'
    | '/quranic-reflections'
    | '/reset-password'
    | '/resources'
    | '/saved'
    | '/sitemap.xml'
    | '/tazkiyah-toolkit'
    | '/young-hearts'
    | '/admin'
    | '/auth/callback'
    | '/read/$slug'
    | '/admin/archive'
    | '/admin/faqs'
    | '/admin/formats'
    | '/admin/newsletter'
    | '/admin/reflections'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/'
    | '/admin/pages/'
    | '/admin/pillars/'
    | '/admin/pages/$key/builder'
    | '/admin/pillars/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$pageSlug'
    | '/about'
    | '/auth'
    | '/contact'
    | '/join'
    | '/life-architecture'
    | '/quranic-reflections'
    | '/reset-password'
    | '/resources'
    | '/saved'
    | '/sitemap.xml'
    | '/tazkiyah-toolkit'
    | '/young-hearts'
    | '/auth/callback'
    | '/read/$slug'
    | '/admin/archive'
    | '/admin/faqs'
    | '/admin/formats'
    | '/admin/newsletter'
    | '/admin/reflections'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/pages/$key/builder'
    | '/admin/pillars/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$pageSlug'
    | '/about'
    | '/auth'
    | '/contact'
    | '/join'
    | '/life-architecture'
    | '/quranic-reflections'
    | '/reset-password'
    | '/resources'
    | '/saved'
    | '/sitemap.xml'
    | '/tazkiyah-toolkit'
    | '/young-hearts'
    | '/_authenticated/admin'
    | '/auth/callback'
    | '/read/$slug'
    | '/_authenticated/admin/archive'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/formats'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/reflections'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/articles/$id'
    | '/_authenticated/admin/articles/'
    | '/_authenticated/admin/pages/'
    | '/_authenticated/admin/pillars/'
    | '/_authenticated/admin/pages/$key/builder'
    | '/_authenticated/admin/pillars/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PageSlugRoute: typeof PageSlugRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  LifeArchitectureRoute: typeof LifeArchitectureRoute
  QuranicReflectionsRoute: typeof QuranicReflectionsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TazkiyahToolkitRoute: typeof TazkiyahToolkitRoute
  YoungHeartsRoute: typeof YoungHeartsRoute
  ReadSlugRoute: typeof ReadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/young-hearts': {
      id: '/young-hearts'
      path: '/young-hearts'
      fullPath: '/young-hearts'
      preLoaderRoute: typeof YoungHeartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tazkiyah-toolkit': {
      id: '/tazkiyah-toolkit'
      path: '/tazkiyah-toolkit'
      fullPath: '/tazkiyah-toolkit'
      preLoaderRoute: typeof TazkiyahToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quranic-reflections': {
      id: '/quranic-reflections'
      path: '/quranic-reflections'
      fullPath: '/quranic-reflections'
      preLoaderRoute: typeof QuranicReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-architecture': {
      id: '/life-architecture'
      path: '/life-architecture'
      fullPath: '/life-architecture'
      preLoaderRoute: typeof LifeArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageSlug': {
      id: '/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/$pageSlug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/read/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reflections': {
      id: '/_authenticated/admin/reflections'
      path: '/reflections'
      fullPath: '/admin/reflections'
      preLoaderRoute: typeof AuthenticatedAdminReflectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/formats': {
      id: '/_authenticated/admin/formats'
      path: '/formats'
      fullPath: '/admin/formats'
      preLoaderRoute: typeof AuthenticatedAdminFormatsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/archive': {
      id: '/_authenticated/admin/archive'
      path: '/archive'
      fullPath: '/admin/archive'
      preLoaderRoute: typeof AuthenticatedAdminArchiveRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pillars/': {
      id: '/_authenticated/admin/pillars/'
      path: '/pillars'
      fullPath: '/admin/pillars/'
      preLoaderRoute: typeof AuthenticatedAdminPillarsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages/': {
      id: '/_authenticated/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthenticatedAdminPagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/articles/': {
      id: '/_authenticated/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/articles/$id': {
      id: '/_authenticated/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pillars/$slug/edit': {
      id: '/_authenticated/admin/pillars/$slug/edit'
      path: '/pillars/$slug/edit'
      fullPath: '/admin/pillars/$slug/edit'
      preLoaderRoute: typeof AuthenticatedAdminPillarsSlugEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages/$key/builder': {
      id: '/_authenticated/admin/pages/$key/builder'
      path: '/pages/$key/builder'
      fullPath: '/admin/pages/$key/builder'
      preLoaderRoute: typeof AuthenticatedAdminPagesKeyBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminArchiveRoute: typeof AuthenticatedAdminArchiveRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFormatsRoute: typeof AuthenticatedAdminFormatsRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminReflectionsRoute: typeof AuthenticatedAdminReflectionsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArticlesIdRoute: typeof AuthenticatedAdminArticlesIdRoute
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute
  AuthenticatedAdminPagesIndexRoute: typeof AuthenticatedAdminPagesIndexRoute
  AuthenticatedAdminPillarsIndexRoute: typeof AuthenticatedAdminPillarsIndexRoute
  AuthenticatedAdminPagesKeyBuilderRoute: typeof AuthenticatedAdminPagesKeyBuilderRoute
  AuthenticatedAdminPillarsSlugEditRoute: typeof AuthenticatedAdminPillarsSlugEditRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminArchiveRoute: AuthenticatedAdminArchiveRoute,
    AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
    AuthenticatedAdminFormatsRoute: AuthenticatedAdminFormatsRoute,
    AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
    AuthenticatedAdminReflectionsRoute: AuthenticatedAdminReflectionsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminArticlesIdRoute: AuthenticatedAdminArticlesIdRoute,
    AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
    AuthenticatedAdminPagesIndexRoute: AuthenticatedAdminPagesIndexRoute,
    AuthenticatedAdminPillarsIndexRoute: AuthenticatedAdminPillarsIndexRoute,
    AuthenticatedAdminPagesKeyBuilderRoute:
      AuthenticatedAdminPagesKeyBuilderRoute,
    AuthenticatedAdminPillarsSlugEditRoute:
      AuthenticatedAdminPillarsSlugEditRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PageSlugRoute: PageSlugRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  LifeArchitectureRoute: LifeArchitectureRoute,
  QuranicReflectionsRoute: QuranicReflectionsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TazkiyahToolkitRoute: TazkiyahToolkitRoute,
  YoungHeartsRoute: YoungHeartsRoute,
  ReadSlugRoute: ReadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
